-- This file is autogenerated by matugen
local M = {}

function M.apply()
  local set = vim.api.nvim_set_hl

  -- Base
  set(0, "Normal",       { fg = "{{colors.on_surface.default.hex}}", bg = "none" })
  set(0, "Comment",      { fg = "{{colors.on_surface_variant.default.hex}}", italic = true })
  set(0, "LineNr",       { fg = "{{colors.surface_variant.default.hex}}" })
  set(0, "CursorLineNr", { fg = "{{colors.primary.default.hex}}", bold = true })

  -- Syntax
  set(0, "Keyword",  { fg = "{{colors.primary.default.hex}}" })
  set(0, "String",   { fg = "{{colors.tertiary.default.hex}}" })
  set(0, "Function", { fg = "{{colors.secondary.default.hex}}" })
  set(0, "Type",     { fg = "{{colors.primary.default.hex}}" })

  -- Visual
  set(0, "Visual", { bg = "{{colors.secondary_container.default.hex}}" })

end

return M
